# ==============================================================================
# Homelab Topology Ansible Inventory
# ==============================================================================

[proxmox_node]
pve                ansible_host=100.121.209.85 ansible_user=root

[ci_runners]
gha-runner-01      ansible_host=10.99.20.101 ansible_user=root vmid=102
gha-runner-angular ansible_host=10.99.20.103 ansible_user=root vmid=103

[s3_cache]
minio-s3           ansible_host=10.99.20.20  ansible_user=root vmid=104

[homelab:children]
proxmox_node
ci_runners
s3_cache
