---
- name: Provision .NET 8 CI Runner (CT 102)
  hosts: gha-runner-01
  gather_facts: true
  roles:
    - common
    - runner_dotnet

- name: Provision Angular Jest CI Runner (CT 103)
  hosts: gha-runner-angular
  gather_facts: true
  roles:
    - common
    - runner_angular
