---
pve01_access: "{{ lookup('community.sops.sops', inventory_dir ~ '/../secrets/hosts/pve01-access.sops.yaml') | from_yaml }}"
base_root_authorized_keys: "{{ pve01_access.root_authorized_keys }}"
base_root_authorized_keys_revoked: "{{ pve01_access.root_authorized_keys_revoked }}"
base_automation_authorized_keys: "{{ pve01_access.automation_authorized_keys }}"
