# ==============================================================================
# Master OpenTofu Homelab Topology Orchestration
# ==============================================================================
# Provisions CI Runners and S3 Remote Cache on Proxmox VE 8.4 using Multi-Cloud
# Hardware Flavor Abstraction (AWS, GCP, Azure, Hetzner, DigitalOcean).

locals {
  # Resolve hardware specs from flavor catalog
  dotnet_specs  = local.resolve_flavor[var.cloud_provider][var.runner_dotnet_flavor]
  angular_specs = local.resolve_flavor[var.cloud_provider][var.runner_angular_flavor]
  minio_specs   = local.resolve_flavor[var.cloud_provider][var.minio_cache_flavor]

  # Dynamically extract Proxmox host IP/FQDN from endpoint URL
  pve_host_matches = regexall("https?://([^:/]+)", var.proxmox_endpoint)
  pve_host         = length(local.pve_host_matches) > 0 ? local.pve_host_matches[0][0] : "127.0.0.1"
}

# ------------------------------------------------------------------------------
# 1. CT 102: .NET 8 / Docker-in-LXC CI Runner (gha-runner-01)
# ------------------------------------------------------------------------------
module "runner_dotnet" {
  source = "./modules/lxc_runner"

  vm_id          = 102
  node_name      = var.proxmox_node
  hostname       = "gha-runner-01"
  template_file  = var.debian_template
  cores          = local.dotnet_specs.cores
  memory_mb      = local.dotnet_specs.memory_mb
  disk_size_gb   = local.dotnet_specs.disk_gb
  storage_pool   = var.storage_pool
  bridge         = var.bridge
  ip_address     = "10.99.20.101/24"
  gateway        = var.gateway
  nesting        = true
  keyctl         = true
  ssh_public_key = var.ssh_public_key
  tags           = ["ci-runner", "dotnet", "docker", var.cloud_provider, var.runner_dotnet_flavor]
}

# ------------------------------------------------------------------------------
# 2. CT 103: Angular Jest Pure Headless Runner (gha-runner-angular)
# ------------------------------------------------------------------------------
module "runner_angular" {
  source = "./modules/lxc_runner"

  vm_id          = 103
  node_name      = var.proxmox_node
  hostname       = "gha-runner-angular"
  template_file  = var.debian_template
  cores          = local.angular_specs.cores
  memory_mb      = local.angular_specs.memory_mb
  disk_size_gb   = local.angular_specs.disk_gb
  storage_pool   = var.storage_pool
  bridge         = var.bridge
  ip_address     = "10.99.20.103/24"
  gateway        = var.gateway
  nesting        = true
  keyctl         = false
  ssh_public_key = var.ssh_public_key
  tags           = ["ci-runner", "angular", "jest", var.cloud_provider, var.runner_angular_flavor]
}

# ------------------------------------------------------------------------------
# 3. CT 104: MinIO S3 Remote Cache Appliance (minio-s3)
# ------------------------------------------------------------------------------
module "minio_cache" {
  source = "./modules/minio_cache"

  vm_id          = 104
  node_name      = var.proxmox_node
  hostname       = "minio-s3"
  template_file  = var.alpine_template
  cores          = local.minio_specs.cores
  memory_mb      = local.minio_specs.memory_mb
  disk_size_gb   = local.minio_specs.disk_gb
  storage_pool   = var.storage_pool
  bridge         = var.bridge
  ip_address     = "10.99.20.20/24"
  gateway        = var.gateway
  ssh_public_key = var.ssh_public_key
}

# ------------------------------------------------------------------------------
# 4. Generate Dynamic Ansible Inventory
# ------------------------------------------------------------------------------
resource "local_file" "ansible_inventory" {
  filename = "${path.module}/../ansible/inventory/hosts.generated.ini"
  content  = <<-EOT
    # Automatically generated by OpenTofu - DO NOT EDIT MANUALLY
    # Cloud Flavor Provider: ${var.cloud_provider}

    [proxmox_node]
    pve ansible_host=${local.pve_host} ansible_user=root

    [ci_runners]
    gha-runner-01      ansible_host=10.99.20.101 vmid=102 flavor=${var.runner_dotnet_flavor}
    gha-runner-angular ansible_host=10.99.20.103 vmid=103 flavor=${var.runner_angular_flavor}

    [s3_cache]
    minio-s3           ansible_host=10.99.20.20  vmid=104 flavor=${var.minio_cache_flavor}

    [homelab:children]
    proxmox_node
    ci_runners
    s3_cache
  EOT
}
