---
all:
  children:
    pve_hosts:
      hosts:
        pve01:
          ansible_host: 10.99.0.2
          ansible_user: automation
          ansible_ssh_pipelining: true
          ssh_key_name: homelab_pve01_ed25519
          pve_node_name: pve01
          management_source: 10.99.0.1
          guest_network:
            zone: hlab
            vnet: guests
            cidr: 10.99.16.0/24
            gateway: 10.99.16.1
