---
- name: Converge
  hosts: all
  tasks:
    - name: Apply the base role
      ansible.builtin.include_role:
        name: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
