---
# Universal Homelab Group Variables
timezone: "Asia/Bangkok"
isolated_subnet: "10.99.20.0/24"
bridge_interface: "vmbr1"
gateway_ip: "10.99.20.1"

# Remote S3 Cache Endpoints
minio_s3_endpoint: "http://10.99.20.20:9000"
minio_console_port: 9001
minio_api_port: 9000

# GitHub Actions Runner Governance
github_repository: "ugritchaichana/Booth-homelab"
runner_user: "runner"
runner_work_dir: "/home/runner/actions-runner/_work"
