---
- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
  when: not base_container_test_mode | bool

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
