---
- name: Restart Egress DNS
  ansible.builtin.systemd:
    name: homelab-egress-dns.service
    state: restarted
    daemon_reload: true

- name: Apply Firewall Rules
  ansible.builtin.command: /etc/network/if-up.d/homelab-firewall
  register: fw_apply
  changed_when: fw_apply.rc == 0
